### PR TITLE
Fix extra line added after non empty header

### LINKED ISSUE #48: OpamPrinter.FullPos.Preserved.opamfile is not idempotent
It can adds an extra newline after the headers.

This is due to the following code fragment https://github.com/ocaml/opam-file-format/blob/a734db9adc9ccedf0705b3072193c0d7bbd3256d/src/opamPrinter.ml#L721
```ocaml
      let header =
        match orig with
        | [] -> []
        | h::_ ->
          let header =
            get_substring {filename=""; start=(1,0); stop=h.pos.start}
          in
          if header = "" then [] else [header]
      in
      String.concat "\n" (aux header f orig)
```

`header`, when not empty, could contain a trailing newline and `String.concat '\n'` would add another one.

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
@rjbou would you be able to take a look at this ?

**Comment by kit-ty-kate** [comment]
I’m not sure what triggers the bug, but is there any chance you could add a test case showing what is being fixed?

**Comment by hhugo** [comment]
I've added a test

**Comment by hhugo** [comment]
Gentle ping

**Comment by rjbou** [comment]
fix #48

**Comment by rjbou** [comment]
Thanks!

**Pull request merged**
